name: sentiment-analysis
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07
  - certifi=2018.10.15
  # - libedit=3.1
  # - libffi=3.2.1
  # - libgcc-ng=8.2.0
  # - libstdcxx-ng=8.2.0
  # - ncurses=6.0
  - openssl=1.0.2p
  - pip=18.1
  - python=3.6.2
  # - readline=7.0
  - setuptools=40.6.2
  - sqlite=3.23.1
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - astroid==2.0.4
    - cycler==0.10.0
    - isort==4.3.4
    - kiwisolver==1.0.1
    - lazy-object-proxy==1.3.1
    - matplotlib==3.0.2
    - mccabe==0.6.1
    - nltk==3.4
    - numpy==1.15.4
    - pandas==0.23.4
    - pylint==2.1.1
    - pyparsing==2.3.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - scikit-learn==0.20.1
    - scipy==1.1.0
    - singledispatch==3.4.0.3
    - six==1.11.0
    - typed-ast==1.1.0
    - wrapt==1.10.11
# prefix: /home/steven/anaconda2/envs/sentiment-analysis

